### ISSUE TITLE
Technical > Review website implementation

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#109]
- [x] Review the technical implementation of the website.
- [x] Decide whether it needs to be converted to NextJS in order to integrate CMS functionality and allow us to efficiently takeover development.
- [x] Decide whether we are going to continue to host on Netlify or elsewhere (AWS? Github Pages?)
- [ ] Raise in sprint tasks for redevelopment as an outcome of this task.

**Comment by eurolife** [comment]
Based on several factors, using the Netlify CMS is the best option for the site in its current codebase. It is also best at this time to keep the current SvelteKit codebase rather than rewriting it to NextJS. The reasons are:

- The site is already hosted on Netlify hosting
- Netlify CMS is extremely easy to integrate with Github and Netlify hosting to employ a CI/CD workflow which works with both development and content updates.
- Because of the flexibility of the Netlify CMS configuration, little to no restructuring or code changes will be needed to integrate it into the site.
- The website and CMS are all contained inside the same project
- SvelteKit looks to be relatively easy to learn so there won't be a steep learning curve involved if any structural changes are needed to be done to the site.
- Fully implementing the CMS for the blog, jobs, team and maybe other areas that we may want editable will most likely take less than a week, possibly only a few days.
