### ISSUE TITLE
Website admins can edit blogs and news articles

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#110]
CPR website admins should be able to use a CMS to add and edit some content on the website:

### Higher priority
- [x]  News articles (Press)
- [x]  Blog posts
- [x]  Jobs
- [x]  Team
- [ ]  Partners

**Comment by eurolife** [comment]
Based on several factors, it looks like using the Netlify CMS is the best option for the site in its current codebase. It is also best at this time to keep the current SvelteKit codebase rather than rewriting it to NextJS. The reasons are:
- The site is already hosted on Netlify hosting
- Netlify CMS is extremely easy to integrate with Github and Netlify hosting to employ a CI/CD workflow which works with both development and content updates.
- Because of the flexibility of the Netlify CMS, no restructuring or code changes will be needed to integrate it into the site.
- The website and CMS are all contained inside the same project
- SvelteKit looks to be relatively easy to learn so there won't be a steep learning curve involved if any structural changes are needed to be done to the site.

**Comment by eurolife** [comment]
Issue moved to [climatepolicyradar/website #16](https://github.com/climatepolicyradar/website/issues/16) via [**ZenHub**](https://www.zenhub.com/)
