### ISSUE TITLE
Map CCLW sector and instrument definitions to CPR definitions

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/policy-search#53]
Mapping should be in the following format for sectors and instruments, with corresponding header row names. Sector and instrument mappings should exist in two separate sheets.

### Instrument format 
```
instrument_CCLW | instrument_CPR
... | ...
```

### Sector format 
```
sector_CCLW | sector_CPR
... | ...
```

Tasks:

- [x] @marcusodavies to provide mapping
- [x] @chrisaballard update instrument and sector schema files `instruments.yml` and `sectors.yml` that are used to drive the filtering selections

**Comment by marcusodavies** [comment]
This document can be found [here](https://docs.google.com/spreadsheets/d/1mIuu-qmpyDP54LBu2mcR43_kkvpTCdFRz2DQwwRsMdk/edit#gid=2091507983). 

In order to facilitate mapping, I have made the following changes to the CPR labelling system:

- Added the following instruments: 'Ecosystem restoration and nature-based solutions'; 'International cooperation'; and 'Monitoring, reporting, verification'
-

- Added the following sectors: 'Cross-cutting areas'; 'Economy-wide'; 'Public sector'; 'Water'; and 'Other'. (Note that 'Other' is under review, pending discussing with CCLW). 

- Aggregated the instruments 'Standards' and 'Obligations' into the single instrument 'Standards and Obligations'. 

These changes have been reflected in the 'Sector keywords' and 'Instrument keywords' [Google sheets](https://docs.google.com/spreadsheets/d/1KvmtGUYIqsoHT2RWLUAhxayNO24g7yBL1W3SNu8gjSQ/edit#gid=1650249149).

Sectors and instruments were mapped to the second 'level' of granularity within the CPR labelling system – for example, the CCLW instrument 'research and development' was mapped to the instrument 'knowledge generation', as opposed to the instrument group 'capacity building'. 

To facilitate mapping, the following exceptions to this practice are:

-  the CCLW sectors 'Agriculture'; 'Buildings'; 'Energy'; 'Industry'; 'LULUCF'; and 'Residential and commercial'.
- the CCLW instruments 'Capacity building - general'.

The above exceptions were instead mapped to the top 'level' of granularity – for example, the sector 'Agriculture' was mapped to the top-level sector 'Agriculture, forestry and other land use'.

**Comment by chrisaballard** [comment]
@marcusodavies I have a question about the following:

> 
> To facilitate mapping, the following exceptions to this practice are:
> 
>     * the CCLW sectors 'Agriculture'; 'Buildings'; 'Energy'; 'Industry'; 'LULUCF'; and 'Residential and commercial'.
> 
>     * the CCLW instruments 'Capacity building - general'.
> 
> 
> The above exceptions were instead mapped to the top 'level' of granularity – for example, the sector 'Agriculture' was mapped to the top-level sector 'Agriculture, forestry and other land use'.

Should those sectors which were mapped to the top level sector, actually have been mapped to the "general" subsector instead? For example: "Agriculture" -> "Agriculture (general)".

I think this will make mapping and filtering easier, because we know that all sectors and instruments have been mapped to the lower level.

**Comment by marcusodavies** [comment]
@chrisaballard happy to go with that approach. 

As you say, some sectors already contain a 'general' subsector - but some don't (which is why I mapped them to the top level sector instead). 

If it's easiest for mapping and filtering, I will create 'general' subsectors and sub-instruments so that you can assign the CCLW sectors to them.

**Comment by chrisaballard** [comment]
@marcusodavies yes, I think its better to create a general subsector/subinstrument in all cases. That way they are all defined at the lower level

**Comment by chrisaballard** [comment]
I have updated the schema definitions for sector and instruments. Also added copies of the source csv instrument and sector keyword files to make sure that they are version controlled. I also updated the schema yaml file creation script to handle missing keyword lists which now occur for some levels.

**Comment by chrisaballard** [comment]
This task is now complete - all cclw sector/instruments are mapped to cpr schema definitions
